### ISSUE TITLE
initial TODO list

### ISSUE THREAD

**Issue by simpixelated** [Loop33/photo-gallery-component#1]
TODO:
* [x] write all code for parent component to show usage (with `onChange` handlers)
* [ ] define deliverables (single HTML file?)
* [ ] include more example data (real image urls)
* [x] create a GitHub repo with all code + instructions
